//! Schema-derived artifacts: the terminal description and a Markdown reference.
//! (The Rust front end is generated by `ifx-gen` instead.)

use clap::ValueEnum;

use crate::schema::{FieldSchema, ResourceSchema};

#[derive(Clone, Copy, Debug, PartialEq, Eq, ValueEnum)]
pub enum Lang {
    /// Markdown reference.
    Markdown,
}

pub fn generate(lang: Lang, schemas: &[ResourceSchema]) -> String {
    match lang {
        Lang::Markdown => markdown(schemas),
    }
}

/// Terminal-friendly description.
pub fn describe(schemas: &[ResourceSchema]) -> String {
    let mut s = String::new();
    for r in schemas {
        s.push_str(&format!("{}\n", r.type_name));
        if !r.doc.is_empty() {
            s.push_str(&format!("  {}\n", r.doc));
        }
        s.push_str("  inputs:\n");
        for f in &r.inputs {
            s.push_str(&format!("    {}\n", field_line(f)));
        }
        if !r.outputs.is_empty() {
            s.push_str("  outputs:\n");
            for f in &r.outputs {
                s.push_str(&format!("    {}: {}  {}\n", f.name, f.ty.display(), f.doc));
            }
        }
        s.push('\n');
    }
    s
}

fn field_line(f: &FieldSchema) -> String {
    let mut flags = Vec::new();
    if f.required {
        flags.push("required".to_string());
    }
    if let Some(d) = &f.default {
        flags.push(format!("default={d}"));
    }
    if f.replace {
        flags.push("replace".into());
    }
    if f.sensitive {
        flags.push("sensitive".into());
    }
    let flags = if flags.is_empty() {
        String::new()
    } else {
        format!(" [{}]", flags.join(", "))
    };
    format!("{}: {}{}  {}", f.name, f.ty.display(), flags, f.doc)
}

/// `linode.instance` -> (`linode`, `instance`)
pub fn split_type(type_name: &str) -> (&str, &str) {
    type_name.split_once('.').unwrap_or(("", type_name))
}

fn markdown(schemas: &[ResourceSchema]) -> String {
    let mut s = String::from(
        "# Resource types\n\n> Generated from the built-in resource schemas. Run `cargo run -p ifx-cli -- stubs markdown -o docs/resources.md`; do not edit by hand.\n\n",
    );
    for r in schemas {
        s.push_str(&format!("## `{}`\n\n{}\n\n", r.type_name, r.doc));
        s.push_str("| input | type | flags | description |\n|---|---|---|---|\n");
        for f in &r.inputs {
            let mut flags = Vec::new();
            if f.required {
                flags.push("required".to_string());
            }
            if let Some(d) = &f.default {
                flags.push(format!("default `{d}`"));
            }
            if f.replace {
                flags.push("replace".into());
            }
            if f.sensitive {
                flags.push("sensitive".into());
            }
            s.push_str(&format!(
                "| `{}` | `{}` | {} | {} |\n",
                markdown_cell(&f.name),
                markdown_cell(&f.ty.display()),
                markdown_cell(&flags.join(", ")),
                markdown_cell(&f.doc)
            ));
        }
        if !r.outputs.is_empty() {
            s.push_str("\n| output | type | description |\n|---|---|---|\n");
            for f in &r.outputs {
                s.push_str(&format!(
                    "| `{}` | `{}` | {} |\n",
                    markdown_cell(&f.name),
                    markdown_cell(&f.ty.display()),
                    markdown_cell(&f.doc)
                ));
            }
        }
        s.push('\n');
    }
    s
}

fn markdown_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', "<br>")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::{FieldType, field};

    #[test]
    fn markdown_escapes_table_separators() {
        let schema = ResourceSchema::new("test.value", "A value | for documentation.")
            .input(field("state", FieldType::open_enum(["on", "off"])).doc("on | off"))
            .output(field("result", FieldType::String).doc("left | right"));

        let generated = generate(Lang::Markdown, &[schema]);
        assert!(generated.contains("\\|"), "{generated}");
        assert!(!generated.contains(r#"`"on" | "off"`"#));
        assert!(generated.contains("on \\| off"));
        assert!(generated.contains("left \\| right"));
    }
}
