[package]
name = "ifx-program"
description = "Lightweight Rust authoring surface for IFX Program IR."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
[features]
default = ["host", "linode", "qemu"]
host = []
linode = []
qemu = []

[dependencies]
anyhow.workspace = true
bon.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
