//! Rust authoring API: one module per provider with, for every resource type, a marker type,
//! a `bon` builder over its inputs (typestate for required fields and exclusive groups),
//! typed output accessors on `Handle<Marker>`, and a `Stack::<provider>_<kind>()` entry.

use std::fmt::Write as _;

use ifx::schema::{FieldSchema, FieldType, ResourceSchema};
use ifx::stubs::split_type;

pub fn provider_module(provider: &str, schemas: &[&ResourceSchema]) -> String {
    let mut o = String::new();
    let _ = writeln!(
        o,
        "//! `{provider}.*` resources for Rust stacks. Generated by `cargo run -p ifx-gen` \
         from the resource schemas; do not edit.\n\
         #![allow(clippy::all, unused_imports, dead_code, non_camel_case_types)]\n\n\
         use std::collections::BTreeMap;\n\n\
         use bon::Builder;\n\
         use serde::Serialize;\n\n\
         use crate::model::{{Connection, ResourceDecl, Urn}};\n\
         use crate::stack::{{Declare, Handle, Input, ResourceType, Stack}};\n"
    );
    let mut types = Vec::new(); // auxiliary enums / object structs, emitted once by name
    for s in schemas {
        resource(&mut o, provider, s, &mut types);
    }
    o
}

// ------------------------------------------------------------------------- naming

pub fn camel(s: &str) -> String {
    let mut out = String::new();
    let mut up = true;
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            if up {
                out.extend(c.to_uppercase());
                up = false;
            } else {
                out.push(c.to_ascii_lowercase());
            }
        } else {
            up = true;
        }
    }
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

fn snake(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect()
}

fn ident(name: &str) -> String {
    const KEYWORDS: &[&str] = &[
        "type", "match", "ref", "self", "mod", "use", "fn", "let", "loop", "move", "struct",
        "enum", "impl", "trait", "pub", "in", "as", "if", "else", "for", "while", "true", "false",
        "where", "box", "static", "const", "crate", "super", "unsafe", "async", "await", "dyn",
        "return", "break", "continue",
    ];
    let s = snake(name);
    if KEYWORDS.contains(&s.as_str()) {
        format!("r#{s}")
    } else {
        s
    }
}

fn doc(o: &mut String, text: &str, indent: &str) {
    for line in text.lines() {
        let _ = writeln!(o, "{indent}/// {line}");
    }
}

// ------------------------------------------------------------------------- types

/// Auxiliary type (enum or object struct) collected while walking a schema.
struct Aux {
    name: String,
}

fn push_aux(types: &mut Vec<Aux>, aux: Aux) {
    if !types.iter().any(|t| t.name == aux.name) {
        types.push(aux);
    }
}

/// Rust type for an input field's value (without the outer `Option`).
fn value_ty(owner: &str, f: &FieldSchema, types: &mut Vec<Aux>, out: &mut String) -> String {
    match &f.ty {
        FieldType::String => "Input<String>".into(),
        FieldType::Int => "Input<i64>".into(),
        FieldType::Float => "Input<f64>".into(),
        FieldType::Bool => "Input<bool>".into(),
        FieldType::Connection => "Input<Connection>".into(),
        FieldType::Any => "Input<serde_json::Value>".into(),
        FieldType::Enum { variants, open } => {
            let name = format!("{owner}{}", camel(&f.name));
            let code = enum_code(&name, variants, *open);
            push_aux(types, Aux { name: name.clone() });
            if !out.contains(&format!("pub enum {name} ")) {
                out.push_str(&code);
            }
            format!("Input<{name}>")
        }
        FieldType::List { item } => {
            format!("Input<Vec<{}>>", item_ty(owner, &f.name, item, types, out))
        }
        FieldType::Map { value } => {
            format!(
                "Input<BTreeMap<String, {}>>",
                item_ty(owner, &f.name, value, types, out)
            )
        }
        FieldType::Object { name, fields } => {
            let name = name
                .clone()
                .unwrap_or_else(|| format!("{owner}{}", camel(&f.name)));
            object_struct(&name, fields, types, out);
            name
        }
    }
}

/// Element type inside a list or map.
fn item_ty(
    owner: &str,
    field: &str,
    t: &FieldType,
    types: &mut Vec<Aux>,
    out: &mut String,
) -> String {
    match t {
        FieldType::Object { name, fields } => {
            let name = name
                .clone()
                .unwrap_or_else(|| format!("{owner}{}", camel(field)));
            object_struct(&name, fields, types, out);
            name
        }
        FieldType::Enum { variants, open } => {
            let name = format!("{owner}{}", camel(field));
            let code = enum_code(&name, variants, *open);
            push_aux(types, Aux { name: name.clone() });
            if !out.contains(&format!("pub enum {name} ")) {
                out.push_str(&code);
            }
            format!("Input<{name}>")
        }
        FieldType::List { item } => format!("Vec<{}>", item_ty(owner, field, item, types, out)),
        FieldType::Map { value } => {
            format!(
                "BTreeMap<String, {}>",
                item_ty(owner, field, value, types, out)
            )
        }
        other => value_ty(owner, &FieldSchema::new(field, other.clone()), types, out),
    }
}

/// Type of an output accessor on `Handle<_>`.
fn output_ty(t: &FieldType) -> String {
    match t {
        FieldType::String | FieldType::Enum { .. } => "String".into(),
        FieldType::Int => "i64".into(),
        FieldType::Float => "f64".into(),
        FieldType::Bool => "bool".into(),
        FieldType::Connection => "Connection".into(),
        FieldType::Any | FieldType::Object { .. } => "serde_json::Value".into(),
        FieldType::List { item } => format!("Vec<{}>", output_ty(item)),
        FieldType::Map { value } => format!("BTreeMap<String, {}>", output_ty(value)),
    }
}

fn enum_code(name: &str, variants: &[String], open: bool) -> String {
    let mut o = String::new();
    let _ = writeln!(o, "\n#[derive(Clone, Debug, PartialEq, Eq)]");
    let _ = writeln!(o, "pub enum {name} {{");
    for v in variants {
        let _ = writeln!(o, "    /// `{v}`");
        let _ = writeln!(o, "    {},", camel(v));
    }
    if open {
        let _ = writeln!(o, "    /// Any value not in the catalog.");
        let _ = writeln!(o, "    Custom(String),");
    }
    let _ = writeln!(o, "}}\n");
    let _ = writeln!(o, "impl {name} {{");
    let _ = writeln!(o, "    pub fn as_str(&self) -> &str {{");
    let _ = writeln!(o, "        match self {{");
    for v in variants {
        let _ = writeln!(o, "            Self::{} => {v:?},", camel(v));
    }
    if open {
        let _ = writeln!(o, "            Self::Custom(s) => s,");
    }
    let _ = writeln!(o, "        }}\n    }}\n}}\n");
    let _ = writeln!(
        o,
        "impl Serialize for {name} {{\n    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {{\n        s.serialize_str(self.as_str())\n    }}\n}}\n"
    );
    let _ = writeln!(
        o,
        "impl std::fmt::Display for {name} {{\n    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{\n        f.write_str(self.as_str())\n    }}\n}}\n"
    );
    if open {
        let _ = writeln!(
            o,
            "impl From<&str> for {name} {{\n    fn from(s: &str) -> Self {{\n        match s {{"
        );
        for v in variants {
            let _ = writeln!(o, "            {v:?} => Self::{},", camel(v));
        }
        let _ = writeln!(
            o,
            "            other => Self::Custom(other.to_string()),\n        }}\n    }}\n}}\n"
        );
        let _ = writeln!(
            o,
            "impl From<String> for {name} {{\n    fn from(s: String) -> Self {{\n        Self::from(s.as_str())\n    }}\n}}\n"
        );
        let _ = writeln!(
            o,
            "impl From<&str> for Input<{name}> {{\n    fn from(s: &str) -> Self {{\n        Input::Value({name}::from(s))\n    }}\n}}\n"
        );
        let _ = writeln!(
            o,
            "impl From<String> for Input<{name}> {{\n    fn from(s: String) -> Self {{\n        Input::Value({name}::from(s))\n    }}\n}}\n"
        );
        let _ = writeln!(
            o,
            "impl From<Input<String>> for Input<{name}> {{\n    fn from(v: Input<String>) -> Self {{\n        v.map({name}::from)\n    }}\n}}\n"
        );
    } else {
        let _ = writeln!(
            o,
            "impl std::str::FromStr for {name} {{\n    type Err = String;\n\n    fn from_str(s: &str) -> Result<Self, String> {{\n        match s {{"
        );
        for v in variants {
            let _ = writeln!(o, "            {v:?} => Ok(Self::{}),", camel(v));
        }
        let _ = writeln!(
            o,
            "            other => Err(format!(\"{{other:?}} is not one of {}\")),\n        }}\n    }}\n}}\n",
            variants.join(", ")
        );
        let _ = writeln!(
            o,
            "impl TryFrom<Input<String>> for Input<{name}> {{\n    type Error = String;\n\n    /// References convert as-is; a literal must be a variant.\n    fn try_from(v: Input<String>) -> Result<Self, String> {{\n        v.try_map(|s| s.parse())\n    }}\n}}\n"
        );
    }
    o
}

/// A nested object type: plain struct with a bon builder, no stack/name.
fn object_struct(name: &str, fields: &[FieldSchema], types: &mut Vec<Aux>, out: &mut String) {
    if types.iter().any(|t| t.name == name) {
        return;
    }
    types.push(Aux {
        name: name.to_string(),
    });
    let mut o = String::new();
    let mut setters = String::new();
    let _ = writeln!(o, "\n#[derive(Clone, Debug, Serialize, Builder)]");
    let _ = writeln!(
        o,
        "#[builder(start_fn(name = builder), finish_fn(name = build), builder_type = {name}Builder, state_mod = {})]",
        snake(name) + "_state"
    );
    let _ = writeln!(o, "pub struct {name} {{");
    for f in fields {
        let ty = value_ty(name, f, types, out);
        emit_field(&mut o, &mut setters, name, f, &ty, false);
    }
    let _ = writeln!(o, "}}");
    if !setters.is_empty() {
        let st = snake(name) + "_state";
        let _ = writeln!(o, "\nimpl<S: {st}::State> {name}Builder<S> {{{setters}}}");
    }
    out.push_str(&o);
}

/// One struct field plus (for lists/maps/groups) its custom setter text.
fn emit_field(
    o: &mut String,
    setters: &mut String,
    owner: &str,
    f: &FieldSchema,
    ty: &str,
    has_lifetime: bool,
) {
    let lt = if has_lifetime { "'a, " } else { "" };
    let fname = ident(&f.name);
    let st = snake(owner) + "_state";
    let opt = |t: &str| {
        if f.required {
            t.to_string()
        } else {
            format!("Option<{t}>")
        }
    };
    let mut d = f.doc.clone();
    if let Some((other, want)) = &f.required_when {
        let _ = write!(d, " Required when `{other}` is {want}.");
    }
    doc(o, &d, "    ");
    let custom = matches!(f.ty, FieldType::List { .. } | FieldType::Map { .. });
    if custom {
        let _ = writeln!(
            o,
            "    #[builder(setters(vis = \"\", name = {}_internal))]",
            snake(&f.name)
        );
    } else {
        let _ = writeln!(o, "    #[builder(into)]");
    }
    if !f.required {
        let _ = writeln!(o, "    #[serde(skip_serializing_if = \"Option::is_none\")]");
    }
    if f.name != snake(&f.name) || fname.starts_with("r#") {
        let _ = writeln!(o, "    #[serde(rename = {:?})]", f.name);
    }
    let _ = writeln!(o, "    pub {fname}: {},", opt(ty));
    if let FieldType::List { .. } = f.ty {
        let inner = ty.trim_start_matches("Input<Vec<").trim_end_matches(">>");
        let set = format!("{st}::Set{}", camel(&f.name));
        let _ = writeln!(
            setters,
            "\n    /// Set `{}` from any iterator of values or references.\n    pub fn {fname}<I>(self, items: I) -> {owner}Builder<{lt}{set}<S>>\n    where\n        S::{}: {st}::IsUnset,\n        I: IntoIterator,\n        I::Item: Into<{inner}>,\n    {{\n        self.{}_internal(Input::Value(items.into_iter().map(Into::into).collect()))\n    }}",
            f.name,
            camel(&f.name),
            snake(&f.name)
        );
        // Whole-list reference (another resource's list output), e.g. `.names_ref(pkg.installed())`.
        if let Some(elem) = inner
            .strip_prefix("Input<")
            .and_then(|s| s.strip_suffix('>'))
        {
            let _ = writeln!(
                setters,
                "\n    /// Set `{}` from a whole-list value or output reference (`Input<Vec<_>>`).\n    pub fn {}_ref(self, list: Input<Vec<{elem}>>) -> {owner}Builder<{lt}{set}<S>>\n    where\n        S::{}: {st}::IsUnset,\n    {{\n        self.{}_internal(list.map(|v| v.into_iter().map(Input::Value).collect()))\n    }}",
                f.name,
                snake(&f.name),
                camel(&f.name),
                snake(&f.name)
            );
        }
    }
    if let FieldType::Map { .. } = f.ty {
        let inner = ty
            .trim_start_matches("Input<BTreeMap<String, ")
            .trim_end_matches(">>");
        let set = format!("{st}::Set{}", camel(&f.name));
        let _ = writeln!(
            setters,
            "\n    /// Set `{}` from any iterator of `(key, value)` pairs.\n    pub fn {fname}<I, K, V>(self, pairs: I) -> {owner}Builder<{lt}{set}<S>>\n    where\n        S::{}: {st}::IsUnset,\n        I: IntoIterator<Item = (K, V)>,\n        K: Into<String>,\n        V: Into<{inner}>,\n    {{\n        self.{}_internal(Input::Value(pairs.into_iter().map(|(k, v)| (k.into(), v.into())).collect()))\n    }}",
            f.name,
            camel(&f.name),
            snake(&f.name)
        );
    }
}

// ------------------------------------------------------------------------- resources

fn resource(o: &mut String, provider: &str, s: &ResourceSchema, types: &mut Vec<Aux>) {
    let (_, kind) = split_type(&s.type_name);
    let marker = camel(kind);
    let st = snake(&marker) + "_state";
    let builder = format!("{marker}Builder");
    let inputs = format!("{marker}Inputs");

    // Auxiliary types first (they must be defined before use only for readability).
    let mut fields_code = String::new();
    let mut setters = String::new();
    let groups = s.groups();
    let mut emitted_groups: Vec<&str> = Vec::new();

    let _ = writeln!(
        o,
        "\n// ---------------------------------------------------------------- {}",
        s.type_name
    );
    doc(o, &format!("`{}`: {}", s.type_name, s.doc), "");
    let _ = writeln!(o, "#[derive(Clone, Copy, Debug)]\npub struct {marker};\n");
    let _ = writeln!(
        o,
        "impl ResourceType for {marker} {{\n    const TYPE: &'static str = {:?};\n}}",
        s.type_name
    );

    for f in &s.inputs {
        if let Some(g) = &f.group {
            if emitted_groups.contains(&g.as_str()) {
                continue;
            }
            emitted_groups.push(g);
            let members = &groups.iter().find(|(n, _)| n == g).unwrap().1;
            let gname = format!("{marker}{}", camel(g));
            let required = members.iter().any(|m| m.required);
            let mut auxiliary = String::new();
            let variant_tys: Vec<String> = members
                .iter()
                .map(|member| value_ty(&marker, member, types, &mut auxiliary))
                .collect();
            o.push_str(&auxiliary);
            // enum with one variant per member
            let _ = writeln!(
                o,
                "\n/// Exactly one of the `{g}` inputs of `{}`.",
                s.type_name
            );
            let _ = writeln!(o, "#[derive(Clone, Debug, Serialize)]\npub enum {gname} {{");
            for (m, ty) in members.iter().zip(&variant_tys) {
                doc(o, &m.doc, "    ");
                let _ = writeln!(
                    o,
                    "    #[serde(rename = {:?})]\n    {}({ty}),",
                    m.name,
                    camel(&m.name)
                );
            }
            let _ = writeln!(o, "}}");
            // field + hidden setter + custom setters
            let gfield = snake(g);
            let _ = writeln!(
                fields_code,
                "    #[builder(setters(vis = \"\", name = {gfield}_internal))]"
            );
            let _ = writeln!(fields_code, "    #[serde(flatten)]");
            let _ = writeln!(
                fields_code,
                "    pub {gfield}: {},",
                if required {
                    gname.clone()
                } else {
                    format!("Option<{gname}>")
                }
            );
            for (m, ty) in members.iter().zip(&variant_tys) {
                doc(&mut setters, &m.doc, "    ");
                let _ = writeln!(
                    setters,
                    "    pub fn {}(self, v: impl Into<{ty}>) -> {builder}<'a, {st}::Set{}<S>>\n    where\n        S::{}: {st}::IsUnset,\n    {{\n        self.{gfield}_internal({gname}::{}(v.into()))\n    }}\n",
                    ident(&m.name),
                    camel(g),
                    camel(g),
                    camel(&m.name)
                );
            }
            continue;
        }
        let ty = value_ty(&marker, f, types, o);
        emit_field(&mut fields_code, &mut setters, &marker, f, &ty, true);
    }

    // Inputs struct with builder.
    let _ = writeln!(
        o,
        "\n/// Inputs of `{}`; build with [`{marker}::builder`] or [`Stack::{}_{}`].",
        s.type_name,
        snake(provider),
        snake(kind)
    );
    let _ = writeln!(o, "#[derive(Serialize, Builder)]");
    let _ = writeln!(
        o,
        "#[builder(start_fn(name = builder), finish_fn(name = build), builder_type = {builder}, state_mod = {st})]"
    );
    let _ = writeln!(o, "pub struct {inputs}<'a> {{");
    let _ = writeln!(
        o,
        "    /// Resource name; with the type it forms the URN `{}:<name>`.",
        s.type_name
    );
    let _ = writeln!(
        o,
        "    #[builder(start_fn, into)]\n    #[serde(skip)]\n    pub resource_name: String,"
    );
    let _ = writeln!(
        o,
        "    #[builder(field)]\n    #[serde(skip)]\n    stack: Option<&'a mut Stack>,"
    );
    let _ = writeln!(
        o,
        "    #[builder(field)]\n    #[serde(skip)]\n    depends_on: Vec<Urn>,"
    );
    let _ = writeln!(
        o,
        "    #[builder(field)]\n    #[serde(skip)]\n    triggers: Vec<Urn>,"
    );
    let _ = writeln!(
        o,
        "    #[builder(field)]\n    #[serde(skip)]\n    protect: bool,"
    );
    o.push_str(&fields_code);
    let _ = writeln!(o, "}}");

    let _ = writeln!(
        o,
        "\nimpl {marker} {{\n    /// Start declaring a `{}` named `name`; finish with `.build()` and `stack.add(..)`.\n    pub fn builder(name: impl Into<String>) -> {builder}<'static> {{\n        {inputs}::builder(name)\n    }}\n}}",
        s.type_name
    );

    // Custom setters + graph options.
    let _ = writeln!(o, "\nimpl<'a, S: {st}::State> {builder}<'a, S> {{");
    o.push_str(&setters);
    let _ = writeln!(
        o,
        "    /// Order this resource after `h` even though no input references it.\n    pub fn depends_on<R>(mut self, h: &Handle<R>) -> Self {{\n        self.depends_on.push(h.urn().clone());\n        self\n    }}\n\n    /// Re-apply this resource whenever `h` changes in the same run.\n    pub fn triggered_by<R>(mut self, h: &Handle<R>) -> Self {{\n        self.triggers.push(h.urn().clone());\n        self\n    }}\n\n    /// Refuse to delete or replace this resource.\n    pub fn protect(mut self) -> Self {{\n        self.protect = true;\n        self\n    }}\n}}"
    );

    // Finisher that registers with the stack.
    let _ = writeln!(
        o,
        "\nimpl<'a, S: {st}::IsComplete> {builder}<'a, S> {{\n    /// Register the resource with the stack this builder was started from.\n    pub fn add(mut self) -> anyhow::Result<Handle<{marker}>> {{\n        let stack = self.stack.take().ok_or_else(|| anyhow::anyhow!(\"{}: builder was not started from a Stack; use .build() and stack.add(..)\"))?;\n        stack.add(self.build())\n    }}\n}}",
        s.type_name
    );

    // Declare impl.
    let _ = writeln!(
        o,
        "\nimpl Declare for {inputs}<'_> {{\n    type Type = {marker};\n\n    fn into_decl(self) -> anyhow::Result<ResourceDecl> {{\n        let inputs = crate::stack::strip_nulls(serde_json::to_value(&self)?);\n        let mut decl = ResourceDecl::new({:?}, &self.resource_name, inputs);\n        decl.depends_on = self.depends_on;\n        decl.triggers = self.triggers;\n        decl.protect = self.protect;\n        Ok(decl)\n    }}\n}}",
        s.type_name
    );

    // Stack entry point.
    let _ = writeln!(
        o,
        "\nimpl Stack {{\n    /// Declare a `{}`; finish with `.add()`.\n    pub fn {}_{}(&mut self, name: impl Into<String>) -> {builder}<'_> {{\n        let mut b = {inputs}::builder(name);\n        b.stack = Some(self);\n        b\n    }}\n}}",
        s.type_name,
        snake(provider),
        snake(kind)
    );

    // Typed outputs.
    if !s.outputs.is_empty() {
        let _ = writeln!(o, "\nimpl Handle<{marker}> {{");
        for f in &s.outputs {
            doc(o, &f.doc, "    ");
            let _ = writeln!(
                o,
                "    pub fn {}(&self) -> Input<{}> {{\n        self.output({:?})\n    }}",
                ident(&f.name),
                output_ty(&f.ty),
                f.name
            );
        }
        let _ = writeln!(o, "}}");
    }
}

#[cfg(test)]
mod tests {
    use ifx::schema::{FieldType, ResourceSchema, field};

    use super::provider_module;

    #[test]
    fn group_member_auxiliary_types_are_emitted_before_the_group_enum() {
        let schema = ResourceSchema::new("test.thing", "test")
            .input(field("image", FieldType::open_enum(["public/image"])).group("source"))
            .input(field("backup_id", FieldType::Int).group("source"));
        let generated = provider_module("test", &[&schema]);
        let auxiliary = generated.find("pub enum ThingImage").unwrap();
        let group = generated.find("pub enum ThingSource").unwrap();
        assert!(auxiliary < group, "{generated}");
    }
}
